<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>
$inverse_primary = rgba(d649aeff)
$on_primary = rgba(241523ff)
$on_primary_container = rgba(241523ff)
$on_primary_fixed = rgba(241523ff)
$on_primary_fixed_variant = rgba(241523ff)
$primary = rgba(d649aeff)
$primary_container = rgba(d649aeff)
$primary_fixed = rgba(d649aeff)
$primary_fixed_dim = rgba(d649aeff)
$source_color = rgba(d649aeff)
$surface_tint = rgba(d649aeff)
