[Unit]
PartOf=hyprland-session.target
After=graphical-session.target

[Install]
# Clear the package default dependency.
WantedBy=
# Start Sunshine with the Hyprland session target, which this config
# explicitly starts on each login.
WantedBy=hyprland-session.target
